spring.profiles.active: default
server.port: 8085
spring.jpa.database: POSTGRESQL
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://localhost:5432/postgres
spring.datasource.username: postgres
spring.datasource.password: qwer12345
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true



genome:
   dna:
     - code: AAAA
     - code: CCCC
     - code: TTTT
     - code: GGGG


